/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Branches {
  connection_url: string | null;
  created_at: Generated<string>;
  dataset: string;
  display_name: string;
  id: Generated<number | null>;
  parent_branch_id: number | null;
  port: number | null;
  project_id: number;
  slug: string;
  source_replay_at: string | null;
  status: Generated<string>;
  updated_at: Generated<string>;
}

export interface JobLogs {
  created_at: Generated<string>;
  id: Generated<number | null>;
  job_id: number;
  level: Generated<string>;
  message: string;
}

export interface Jobs {
  created_at: Generated<string>;
  error: string | null;
  finished_at: string | null;
  id: Generated<number | null>;
  input_json: string | null;
  started_at: string | null;
  status: Generated<string>;
  type: string;
  updated_at: Generated<string>;
}

export interface Projects {
  app_user: Generated<string>;
  created_at: Generated<string>;
  database_name: Generated<string>;
  id: Generated<number | null>;
  name: string;
  postgres_version: Generated<string>;
  updated_at: Generated<string>;
}

export interface SchemaMigrations {
  applied_at: Generated<string>;
  id: string | null;
}

export interface Servers {
  created_at: Generated<string>;
  host: string;
  id: Generated<number | null>;
  last_checked_at: string | null;
  role: string;
  ssh_key_path: string;
  ssh_user: string;
  status: Generated<string>;
  status_message: string | null;
  updated_at: Generated<string>;
}

export interface Settings {
  created_at: Generated<string>;
  key: string | null;
  updated_at: Generated<string>;
  value: string;
}

export interface SetupSteps {
  id: Generated<number | null>;
  key: string;
  label: string;
  message: string | null;
  status: Generated<string>;
  updated_at: Generated<string>;
}

export interface DB {
  branches: Branches;
  job_logs: JobLogs;
  jobs: Jobs;
  projects: Projects;
  schema_migrations: SchemaMigrations;
  servers: Servers;
  settings: Settings;
  setup_steps: SetupSteps;
}
