/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Branches {
  connectionUrl: string | null;
  createdAt: Generated<string>;
  dataset: string;
  displayName: string;
  id: Generated<number | null>;
  parentBranchId: number | null;
  port: number | null;
  projectId: number;
  slug: string;
  sourceReplayAt: string | null;
  expiresAt: string | null;
  status: Generated<string>;
  updatedAt: Generated<string>;
}

export interface JobLogs {
  createdAt: Generated<string>;
  id: Generated<number | null>;
  jobId: number;
  level: Generated<string>;
  message: string;
}

export interface Jobs {
  createdAt: Generated<string>;
  error: string | null;
  finishedAt: string | null;
  id: Generated<number | null>;
  inputJson: string | null;
  startedAt: string | null;
  status: Generated<string>;
  type: string;
  updatedAt: Generated<string>;
}

export interface Projects {
  appUser: Generated<string>;
  createdAt: Generated<string>;
  databaseName: Generated<string>;
  id: Generated<number | null>;
  name: string;
  postgresVersion: Generated<string>;
  updatedAt: Generated<string>;
}

export interface SchemaMigrations {
  appliedAt: Generated<string>;
  id: string | null;
}

export interface Servers {
  createdAt: Generated<string>;
  host: string;
  id: Generated<number | null>;
  lastCheckedAt: string | null;
  role: string;
  sshKeyPath: string;
  sshUser: string;
  status: Generated<string>;
  statusMessage: string | null;
  updatedAt: Generated<string>;
}

export interface Settings {
  createdAt: Generated<string>;
  key: string | null;
  updatedAt: Generated<string>;
  value: string;
}

export interface SetupSteps {
  id: Generated<number | null>;
  key: string;
  label: string;
  message: string | null;
  status: Generated<string>;
  updatedAt: Generated<string>;
}

export interface DB {
  branches: Branches;
  jobLogs: JobLogs;
  jobs: Jobs;
  projects: Projects;
  schemaMigrations: SchemaMigrations;
  servers: Servers;
  settings: Settings;
  setupSteps: SetupSteps;
}
