/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BranchBranchIdSqlRouteImport } from './routes/branch/$branchId/sql'
import { Route as BranchBranchIdOverviewRouteImport } from './routes/branch/$branchId/overview'
import { Route as BranchBranchIdBackupRestoreRouteImport } from './routes/branch/$branchId/backup-restore'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchBranchIdSqlRoute = BranchBranchIdSqlRouteImport.update({
  id: '/branch/$branchId/sql',
  path: '/branch/$branchId/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchBranchIdOverviewRoute = BranchBranchIdOverviewRouteImport.update({
  id: '/branch/$branchId/overview',
  path: '/branch/$branchId/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchBranchIdBackupRestoreRoute =
  BranchBranchIdBackupRestoreRouteImport.update({
    id: '/branch/$branchId/backup-restore',
    path: '/branch/$branchId/backup-restore',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/branch/$branchId/backup-restore': typeof BranchBranchIdBackupRestoreRoute
  '/branch/$branchId/overview': typeof BranchBranchIdOverviewRoute
  '/branch/$branchId/sql': typeof BranchBranchIdSqlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/branch/$branchId/backup-restore': typeof BranchBranchIdBackupRestoreRoute
  '/branch/$branchId/overview': typeof BranchBranchIdOverviewRoute
  '/branch/$branchId/sql': typeof BranchBranchIdSqlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/branch/$branchId/backup-restore': typeof BranchBranchIdBackupRestoreRoute
  '/branch/$branchId/overview': typeof BranchBranchIdOverviewRoute
  '/branch/$branchId/sql': typeof BranchBranchIdSqlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/branch/$branchId/backup-restore'
    | '/branch/$branchId/overview'
    | '/branch/$branchId/sql'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/branch/$branchId/backup-restore'
    | '/branch/$branchId/overview'
    | '/branch/$branchId/sql'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/branch/$branchId/backup-restore'
    | '/branch/$branchId/overview'
    | '/branch/$branchId/sql'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  BranchBranchIdBackupRestoreRoute: typeof BranchBranchIdBackupRestoreRoute
  BranchBranchIdOverviewRoute: typeof BranchBranchIdOverviewRoute
  BranchBranchIdSqlRoute: typeof BranchBranchIdSqlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/$branchId/sql': {
      id: '/branch/$branchId/sql'
      path: '/branch/$branchId/sql'
      fullPath: '/branch/$branchId/sql'
      preLoaderRoute: typeof BranchBranchIdSqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/$branchId/overview': {
      id: '/branch/$branchId/overview'
      path: '/branch/$branchId/overview'
      fullPath: '/branch/$branchId/overview'
      preLoaderRoute: typeof BranchBranchIdOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/$branchId/backup-restore': {
      id: '/branch/$branchId/backup-restore'
      path: '/branch/$branchId/backup-restore'
      fullPath: '/branch/$branchId/backup-restore'
      preLoaderRoute: typeof BranchBranchIdBackupRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  BranchBranchIdBackupRestoreRoute: BranchBranchIdBackupRestoreRoute,
  BranchBranchIdOverviewRoute: BranchBranchIdOverviewRoute,
  BranchBranchIdSqlRoute: BranchBranchIdSqlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
